### PR TITLE
Improve coding standards, add a gitignore

### PR DESCRIPTION
**Pull request by md5sha256**
Hello! This PR aims to improve the overall coding standard of the plugin and improve the readability of the code. I have mostly fixed the improper use of the primitive wrapper classes, inverted a few if-statements and moved all Sql Statements to be PreparedStatements. I have also added a gitignore.

### CODE REVIEW

**Comment by Rosstail** [comment]
Hi, thanks for your code improve, especially for improves and readability (You even see in my code some orthographics errors, thx XD). The fact is few days ago without pushing, I've modified some little things in the code, like classes constructors.

In that case, should I push my code before I merge yours ?

**Comment by md5sha256** [comment]
Push your changes, git will know how to rebase mine ontop of yours

**Comment by md5sha256** [comment]
Okay, well there are merge conflicts which need to be resolved before this PR can be merged in.

**Comment by Rosstail** [comment]
Okay. I gonna to do some job at home, I'll do it once finished.

**Comment by md5sha256** [comment]
I've gone ahead and rebase + fixed the merge conflicts.

**Comment by Rosstail** [comment]
Nice, many thanks.

**Pull request merged**
